import { pgTable, text, integer, timestamp } from 'drizzle-orm/pg-core'

export const sgThreats = pgTable('sg_threats', { id: text('id').primaryKey(), incidentId: text('incident_id').notNull(), title: text('title').notNull(), severity: text('severity').notNull(), status: text('status').notNull(), srcIp: text('src_ip').notNull(), dstIp: text('dst_ip').notNull(), score: integer('score').notNull(), detectedAt: timestamp('detected_at', { withTimezone: true }).notNull(), mitre: text('mitre').notNull(), details: text('details').notNull() })
export const sgIncidents = pgTable('sg_incidents', { id: text('id').primaryKey(), title: text('title').notNull(), severity: text('severity').notNull(), status: text('status').notNull(), owner: text('owner').notNull(), asset: text('asset').notNull(), summary: text('summary').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull() })
export const sgEvents = pgTable('sg_events', { id: text('id').primaryKey(), incidentId: text('incident_id').notNull(), eventTime: timestamp('event_time', { withTimezone: true }).notNull(), eventType: text('event_type').notNull(), actor: text('actor').notNull(), source: text('source').notNull(), summary: text('summary').notNull(), severity: text('severity').notNull() })
export const sgNetworkNodes = pgTable('sg_network_nodes', { id: text('id').primaryKey(), label: text('label').notNull(), kind: text('kind').notNull(), risk: integer('risk').notNull(), connections: integer('connections').notNull(), lastSeen: timestamp('last_seen', { withTimezone: true }).notNull() })
export const sgAnalyses = pgTable('sg_analyses', { id: text('id').primaryKey(), inputText: text('input_text').notNull(), verdict: text('verdict').notNull(), score: integer('score').notNull(), explanation: text('explanation').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull() })
export const sgActions = pgTable('sg_actions', { id: text('id').primaryKey(), action: text('action').notNull(), target: text('target').notNull(), actor: text('actor').notNull(), status: text('status').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull() })

export const schema = { sgThreats, sgIncidents, sgEvents, sgNetworkNodes, sgAnalyses, sgActions }
