'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { Activity, ArrowLeft, Bot, BrainCircuit, ChevronRight, Database, Filter, Search, ShieldCheck, Sparkles, Target, TriangleAlert } from 'lucide-react'
import { attackCategories, categories, featureContributions, incidents, mlPipeline, modelMetrics, networkEntities, postgresEntities, threats } from '@/lib/stormguard/data'

type Props={kind:'incidents'|'incident'|'timeline'|'analyst'|'explainability'|'explorer'|'data-model'|'settings'; id?:string}
const nav=[['/','Command Center'],['/incidents','Incident Command'],['/timeline','Timeline'],['/analyst','Odin Analyst'],['/explainability','Explainability'],['/explorer','Storm Archive'],['/data-model','UNSW-NB15 Lab'],['/settings','Settings']]
export default function StormGuardRoutePage({kind,id}:Props){
 const [query,setQuery]=useState(''); const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState(''); const [status,setStatus]=useState('ALL')
 const incident=incidents.find(x=>x.id===id)||incidents[0]; const threat=threats.find(x=>x.id===incident.threatIds[0])||threats[0]
 const filtered=useMemo(()=>incidents.filter(x=>(status==='ALL'||x.status===status)&&`${x.id} ${x.title} ${x.source}`.toLowerCase().includes(query.toLowerCase())),[query,status])
 const title=kind==='incidents'?'VALHALLA INCIDENT COMMAND':kind==='incident'?incident.id:kind==='timeline'?'ATTACK TIMELINE':kind==='analyst'?'ODIN AI ANALYST':kind==='explainability'?"ODIN'S ANALYSIS":kind==='explorer'?'STORM ARCHIVE':kind==='data-model'?'UNSW-NB15 DATA LAB':'SYSTEM SETTINGS'
 const submit=()=>{const q=question.toLowerCase();setAnswer(q.includes('danger')||q.includes('critical')?'T-9421 is the most dangerous: risk 98/100 and 94% demo confidence. Preserve WKSTN-442 evidence first.':q.includes('first')?'Investigate INC-2048 first; its path joins reconnaissance, credential access, lateral movement, and command & control.':'I see an active intrusion chain centered on WKSTN-442. Ask what is most dangerous or what to investigate first.')}
 return <div className="stormguard-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck/></div><div><strong>STORMGUARD</strong><span>AI SECURITY OPERATIONS</span></div></div><div className="demo-tag"><span className="live-dot"/>DEMO MODE <span className="demo-divider"/> UNSW-NB15</div><nav className="main-nav">{nav.map(([href,label])=><Link key={href} href={href} className={href===`/${kind}`?'nav-item active':'nav-item'}>{label}</Link>)}</nav><div className="sidebar-bottom"><div className="agent-card"><Bot/><div><strong>ODIN AGENT</strong><span>ONLINE / v0.8.4</span></div><span className="live-dot"/></div></div></aside><main className="main-content"><header className="topbar"><div className="breadcrumb"><Link href="/">COMMAND CENTER</Link><ChevronRight/><strong>{title}</strong></div><div className="system-health"><span className="live-dot"/>SYSTEM NOMINAL</div></header><div className="content-wrap"><div className="page-heading"><div><div className="eyebrow"><span className="pulse-line"/>SOC // DEMO TELEMETRY</div><h1>{title}</h1><p>Deterministic demo workspace. Every value is labeled <b>DEMO MODEL</b> until a trained ML service is connected.</p></div><Link className="outline-button" href="/"><ArrowLeft/>BACK TO COMMAND</Link></div>{kind==='incidents'&&<IncidentList query={query} setQuery={setQuery} status={status} setStatus={setStatus} filtered={filtered}/>} {kind==='incident'&&<IncidentDetail incident={incident} threat={threat}/>} {kind==='timeline'&&<Timeline/>} {kind==='analyst'&&<Analyst question={question} setQuestion={setQuestion} answer={answer} submit={submit}/>} {kind==='explainability'&&<Explainability/>} {kind==='explorer'&&<Explorer query={query} setQuery={setQuery}/>} {kind==='data-model'&&<DataLab/>} {kind==='settings'&&<Settings/>}</div></main></div>
}
function IncidentList({query,setQuery,status,setStatus,filtered}:any){return <><div className="panel route-toolbar"><Search/><input aria-label="Search incidents" placeholder="Search incidents, IPs, entities..." value={query} onChange={e=>setQuery(e.target.value)}/><Filter/><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>OPEN</option><option>INVESTIGATING</option><option>CONTAINED</option></select></div><div className="route-grid">{filtered.map((x:any)=><Link className="panel route-card" href={`/incidents/${x.id}`} key={x.id}><div className="section-label"><span className="section-mark"/>{x.id}<span className={`severity severity-${x.severity.toLowerCase()}`}>{x.severity}</span></div><h2>{x.title}</h2><p>{x.summary}</p><div className="route-facts"><span>RISK <b>{x.risk}</b></span><span>STATUS <b>{x.status}</b></span><span>{x.opened}</span></div></Link>)}</div></>}
function IncidentDetail({incident,threat}:any){return <><div className="route-grid"><div className="panel route-card"><div className="section-label">INCIDENT PROFILE</div><h2>{incident.title}</h2><p>{incident.summary}</p><div className="metric-strip"><b>{incident.risk}<small>/100 RISK</small></b><b>{incident.confidence}%<small>CONFIDENCE</small></b><b>{incident.status}<small>STATUS</small></b></div></div><div className="panel route-card"><div className="section-label">ODIN ASSESSMENT <span className="model-tag">DEMO MODEL</span></div><h2>Containment recommended</h2><p>{threat.detail}</p><button className="contain-button"><ShieldCheck/>ISOLATE HOST</button></div></div><div className="panel route-card"><div className="section-label">EVIDENCE // ATTACK PATH</div><div className="evidence-list">{threat.evidence.map((e:string,i:number)=><div key={e}><span>{i+1}</span><b>{e}</b><small>{i<2?'observed':'correlated'} · {threat.time}</small></div>)}</div></div></>}
function Timeline(){return <div className="panel route-card"><div className="section-label">INC-2048 // DEMO MODEL</div><h2>Reconnaissance to command & control</h2><div className="route-timeline">{['09:28:11 · Reconnaissance · Port sweep detected','09:30:19 · Discovery · DNS entropy spike','09:35:44 · Credential Access · LSASS access blocked','09:39:08 · Lateral Movement · SMB admin share hit','09:41:22 · Command & Control · PowerShell beacon'].map((x,i)=><div key={x}><i className={i===4?'critical':''}/><span>{x}</span></div>)}</div></div>}
function Analyst({question,setQuestion,answer,submit}:any){return <div className="panel analyst-panel"><div className="analyst-header"><Bot/><div><h2>ODIN / SECURITY ANALYST</h2><p>Answers grounded in the deterministic StormGuard demo corpus.</p></div></div><div className="suggestions"><button onClick={()=>setQuestion('What is the most dangerous threat?')}>What is the most dangerous threat?</button><button onClick={()=>setQuestion('What should I investigate first?')}>What should I investigate first?</button></div><div className="chat-answer">{answer||'Ask Odin about threats, incidents, risk, or investigation priority.'}</div><div className="route-toolbar"><input aria-label="Ask Odin" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Ask ODIN..."/><button className="simulation-button" onClick={submit}><Sparkles/>ANALYZE</button></div></div>}
function Explainability(){return <div className="route-grid"><div className="panel route-card"><div className="section-label">SHAP-READY FEATURE CONTRIBUTIONS</div><h2>T-9421 / encoded PowerShell beacon</h2>{featureContributions.map(([name,value])=><div className="feature-bar" key={name}><span>{name}</span><div><i style={{width:`${Math.abs(value)*250}%`}}/></div><b>{value>0?'+':''}{value.toFixed(2)}</b></div>)}</div><div className="panel route-card"><div className="section-label">PIPELINE</div><h2>Inference architecture</h2>{mlPipeline.map((x,i)=><div className="pipeline-step" key={x}><span>{i+1}</span>{x}<ChevronRight/></div>)}</div></div>}
function Explorer({query,setQuery}:any){const rows=[...threats.map(x=>[x.id,x.title,x.host,'THREAT']),...networkEntities.map(x=>[x.id,x.name,x.address,'ENTITY'])].filter(x=>x.join(' ').toLowerCase().includes(query.toLowerCase()));return <><div className="panel route-toolbar"><Search/><input aria-label="Search archive" placeholder="Search threats, incidents, IPs, entities..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="panel archive-table">{rows.map(r=><div key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><small>{r[2]}</small><em>{r[3]}</em></div>)}</div></>}
function DataLab(){return <div className="route-grid"><div className="panel route-card"><div className="section-label">DATASET PROFILE</div><h2>UNSW-NB15 <span className="dataset-tag">DEMO</span></h2><div className="metric-strip"><b>12440<small>FLOWS</small></b><b>10<small>CLASSES</small></b><b>49<small>FEATURES</small></b></div><div className="category-list">{attackCategories.map(x=><div key={x}><span>{x}</span><i style={{width:`${categories[x]}%`}}/><b>{categories[x]}%</b></div>)}</div></div><div className="panel route-card"><div className="section-label">MODEL METRICS // DEMO MODEL</div>{[['Accuracy',modelMetrics.accuracy],['Precision',modelMetrics.precision],['Recall',modelMetrics.recall],['F1 score',modelMetrics.f1]].map(([x,v])=><div className="metric-row" key={x as string}><span>{x as string}</span><b>{((v as number)*100).toFixed(1)}%</b></div>)}<div className="confusion"><b>CONFUSION MATRIX</b><div>{modelMetrics.confusion.flat().map((x,i)=><span key={i}>{x}</span>)}</div></div></div></div>}
function Settings(){return <div className="route-grid"><div className="panel route-card"><div className="section-label">ENVIRONMENT</div><h2>Demo mode is active</h2><p>StormGuard runs on deterministic UNSW-NB15-compatible fixtures. Connect a Python FastAPI service to replace inference without changing the UI contracts.</p><span className="dataset-tag">DEMO MODEL</span></div><div className="panel route-card"><div className="section-label">DATABASE-READY ENTITIES</div>{postgresEntities.map(x=><div className="pipeline-step" key={x}><Database/>{x}<span className="model-tag">POSTGRES / SUPABASE</span></div>)}</div></div>}
