export type Severity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'
export type IncidentStatus = 'OPEN' | 'INVESTIGATING' | 'CONTAINED' | 'RESOLVED'
export type AttackCategory = 'Normal' | 'Fuzzers' | 'Analysis' | 'Backdoors' | 'DoS' | 'Exploits' | 'Generic' | 'Reconnaissance' | 'Shellcode' | 'Worms'

export interface Threat { id:string; title:string; type:string; severity:Severity; score:number; confidence:number; time:string; host:string; user:string; source:string; destination:string; tactic:string; detail:string; evidence:string[]; category:AttackCategory }
export interface Incident { id:string; title:string; severity:Severity; risk:number; confidence:number; status:IncidentStatus; source:string; destination:string; opened:string; owner:string; threatIds:string[]; summary:string }
export interface NetworkEntity { id:string; name:string; kind:string; state:'normal'|'medium'|'high'|'critical'; address:string }
export interface SecurityEvent { id:string; incidentId:string; time:string; phase:string; detail:string; severity:Severity }

export const threats: Threat[] = [
 {id:'T-9421',title:'Encoded PowerShell beacon',type:'Command & Control',severity:'CRITICAL',score:98,confidence:94,time:'09:41:22',host:'WKSTN-442',user:'jsmith',source:'10.42.8.14',destination:'185.199.110.153',tactic:'T1059.001',category:'Exploits',detail:'A signed binary proxy execution chain opened an outbound TLS session to a rare ASN after a macro payload ran.',evidence:['powershell.exe -enc payload','Rare ASN / 185.199.110.153','Office child-process chain']},
 {id:'T-9417',title:'Lateral SMB movement',type:'Lateral Movement',severity:'HIGH',score:84,confidence:89,time:'09:39:08',host:'SRV-DB-07',user:'svc_backup',source:'10.42.8.22',destination:'10.42.8.7',tactic:'T1021.002',category:'Reconnaissance',detail:'Unexpected admin share access followed a burst of failed authentication attempts from an unmanaged workstation.',evidence:['14 failed logons','ADMIN$ share access','Unmanaged source host']},
 {id:'T-9403',title:'Credential dumping signature',type:'Credential Access',severity:'HIGH',score:77,confidence:91,time:'09:35:44',host:'WKSTN-119',user:'akhan',source:'10.42.9.41',destination:'10.42.8.5',tactic:'T1003',category:'Backdoors',detail:'Memory access pattern matches a known credential extraction family, but execution was blocked by endpoint policy.',evidence:['LSASS memory access','Endpoint block event','Unsigned child process']},
 {id:'T-9398',title:'DNS tunneling anomaly',type:'Exfiltration',severity:'MEDIUM',score:63,confidence:82,time:'09:30:19',host:'IOT-GW-02',user:'system',source:'10.42.12.9',destination:'8.8.8.8',tactic:'T1048.003',category:'DoS',detail:'High-entropy subdomains exceeded the baseline for this device class across three consecutive intervals.',evidence:['Entropy 7.8','312 unique subdomains','Three interval baseline breach']},
]
export const incidents: Incident[] = [
 {id:'INC-2048',title:'PowerShell beacon chain',severity:'CRITICAL',risk:98,confidence:94,status:'INVESTIGATING',source:'10.42.8.14',destination:'185.199.110.153',opened:'09:41:22 UTC',owner:'Alex Morgan',threatIds:['T-9421'],summary:'Likely initial access to command and control transition on WKSTN-442.'},
 {id:'INC-2047',title:'SMB lateral movement',severity:'HIGH',risk:84,confidence:89,status:'OPEN',source:'10.42.8.22',destination:'10.42.8.7',opened:'09:39:08 UTC',owner:'Unassigned',threatIds:['T-9417'],summary:'Admin share access suggests credential reuse across server segment.'},
 {id:'INC-2046',title:'Credential access attempt',severity:'HIGH',risk:77,confidence:91,status:'CONTAINED',source:'10.42.9.41',destination:'10.42.8.5',opened:'09:35:44 UTC',owner:'N. Chen',threatIds:['T-9403'],summary:'Endpoint policy blocked suspected credential dumping behavior.'},
]
export const networkEntities: NetworkEntity[] = [
 {id:'WKSTN-442',name:'WKSTN-442',kind:'Endpoint',state:'critical',address:'10.42.8.14'}, {id:'SRV-DB-07',name:'SRV-DB-07',kind:'Database',state:'high',address:'10.42.8.7'}, {id:'DC-01',name:'DC-01',kind:'Identity',state:'normal',address:'10.42.8.5'}, {id:'FW-EDGE',name:'FW-EDGE',kind:'Firewall',state:'normal',address:'10.42.0.1'}, {id:'IOT-GW-02',name:'IOT-GW-02',kind:'Gateway',state:'medium',address:'10.42.12.9'}]
export const events: SecurityEvent[] = [
 {id:'E-1',incidentId:'INC-2048',time:'09:28:11',phase:'Reconnaissance',detail:'Port sweep detected',severity:'MEDIUM'}, {id:'E-2',incidentId:'INC-2048',time:'09:30:19',phase:'Discovery',detail:'DNS entropy spike',severity:'MEDIUM'}, {id:'E-3',incidentId:'INC-2048',time:'09:35:44',phase:'Credential Access',detail:'LSASS access blocked',severity:'HIGH'}, {id:'E-4',incidentId:'INC-2048',time:'09:39:08',phase:'Lateral Movement',detail:'SMB admin share hit',severity:'HIGH'}, {id:'E-5',incidentId:'INC-2048',time:'09:41:22',phase:'Command & Control',detail:'PowerShell beacon',severity:'CRITICAL'}]
export const modelMetrics = { model:'DEMO MODEL', version:'XGBoost-compatible v2.1', dataset:'UNSW-NB15', accuracy:0.931, precision:0.918, recall:0.904, f1:0.911, flows:12440, confusion:[[7462,182],[391,4405]] }
export const featureContributions = [['Destination Port',0.31],['Flow Bytes/s',0.24],['Protocol: TCP',0.18],['Connection State',0.11],['Packet Length Mean',0.07],['Source Bytes',-0.04]] as const
export const categories: Record<AttackCategory, number> = {Normal:76.2,Fuzzers:3.8,Analysis:1.2,Backdoors:1.1,DoS:4.9,Exploits:7.8,Generic:3.1,Reconnaissance:1.4,Shellcode:0.4,Worms:0.1}
export function getIncident(id:string){ return incidents.find((item)=>item.id===id) }
export function getThreat(id:string){ return threats.find((item)=>item.id===id) }
export function analyzeQuestion(question:string){ const q=question.toLowerCase(); if(q.includes('danger')||q.includes('critical')) return 'T-9421 is the most dangerous signal: risk 98/100 with 94% demo confidence. Investigate WKSTN-442 and preserve endpoint evidence first.'; if(q.includes('first')||q.includes('investigate')) return 'Start with INC-2048. It connects reconnaissance, blocked credential access, lateral movement, and an active PowerShell beacon.'; return 'ODIN sees an active intrusion chain centered on WKSTN-442. Ask about the most dangerous threat, why it is critical, or what to investigate first.' }
export function analyzePhishing(text:string){ const t=text.toLowerCase(); const indicators=[['Urgency language',/urgent|suspend|immediately|overdue/.test(t)],['Suspicious URL',/http:\/\/|bit\.ly|payrn|login/.test(t)],['Sender anomaly',/payrn|微|acme-payrnents/.test(t)],['Credential request',/password|credential|verify|login/.test(t)]]; const hits=indicators.filter(([,hit])=>hit).map(([label])=>label); return {model:'DEMO MODEL',risk:Math.min(99,38+hits.length*15),verdict:hits.length>=2?'HIGH RISK':'REVIEW',indicators:hits} }
export const postgresEntities = ['threats','incidents','network_entities','events','model_runs','users']
export const mlPipeline = ['UNSW-NB15','preprocessing','feature engineering','intrusion classifier','anomaly detection','risk score','SHAP explanation']
export const attackCategories = Object.keys(categories) as AttackCategory[]
