import { and, desc, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { sgActions, sgAnalyses, sgEvents, sgIncidents, sgNetworkNodes, sgThreats } from '@/lib/db/schema'
import { analyzePhishing, analyzeQuestion, events as demoEvents, incidents as demoIncidents, networkEntities as demoNetwork, threats as demoThreats } from './data'

const demoTime = (value: string) => new Date(`2026-08-30T${value.replace(' UTC','')}Z`)
let seeded = false
export async function ensureSeeded() { if (seeded) return; const existing = await db.select({ id: sgIncidents.id }).from(sgIncidents).limit(1); if (!existing.length) { await db.insert(sgIncidents).values(demoIncidents.map((i) => ({ id:i.id,title:i.title,severity:i.severity,status:i.status,owner:i.owner,asset:i.source,summary:i.summary,createdAt:demoTime(i.opened),updatedAt:demoTime(i.opened) }))); await db.insert(sgThreats).values(demoThreats.map((t) => ({ id:t.id,incidentId:demoIncidents.find(i=>i.threatIds.includes(t.id))?.id ?? 'INC-2048',title:t.title,severity:t.severity,status:'OPEN',srcIp:t.source,dstIp:t.destination,score:t.score,detectedAt:demoTime(t.time),mitre:t.tactic,details:t.detail }))); await db.insert(sgEvents).values(demoEvents.map((e)=>({id:e.id,incidentId:e.incidentId,eventTime:demoTime(e.time),eventType:e.phase,actor:'sensor',source:'UNSW-NB15',summary:e.detail,severity:e.severity}))); await db.insert(sgNetworkNodes).values(demoNetwork.map((n)=>({id:n.id,label:n.name,kind:n.kind,risk:n.state==='critical'?98:n.state==='high'?84:n.state==='medium'?63:18,connections:Math.max(1, demoThreats.filter(t=>t.host===n.name).length),lastSeen:new Date()}))) } seeded = true }
export async function listThreats() { await ensureSeeded(); return db.select().from(sgThreats).orderBy(desc(sgThreats.detectedAt)) }
export async function listIncidents() { await ensureSeeded(); return db.select().from(sgIncidents).orderBy(desc(sgIncidents.updatedAt)) }
export async function getIncident(id:string) { await ensureSeeded(); const [incident] = await db.select().from(sgIncidents).where(eq(sgIncidents.id,id)); const threatRows = await db.select().from(sgThreats).where(eq(sgThreats.incidentId,id)); const eventRows = await db.select().from(sgEvents).where(eq(sgEvents.incidentId,id)).orderBy(sgEvents.eventTime); return { incident, threats:threatRows, events:eventRows } }
export async function listNetwork() { await ensureSeeded(); return db.select().from(sgNetworkNodes).orderBy(desc(sgNetworkNodes.risk)) }
export async function saveAction(action:string,target:string) { const id=`ACT-${Date.now()}`; await db.insert(sgActions).values({id,action,target,actor:'analyst',status:'QUEUED',createdAt:new Date()}); return { id, action, target, status:'QUEUED' } }
export async function runAnalysis(input:string, phishing=false) { const result = phishing ? analyzePhishing(input) : { verdict:'ANALYST REVIEW', risk: input.toLowerCase().includes('powershell') ? 98 : 64, explanation: analyzeQuestion(input) }; const id=`AN-${Date.now()}`; await db.insert(sgAnalyses).values({id,inputText:input,verdict:result.verdict,score:result.risk,explanation:'explanation' in result ? result.explanation : result.indicators.join(', ') || 'No indicators detected.',createdAt:new Date()}); return { ...result, id, model:'DEMO MODEL · persisted in Neon' } }
